version: "3.9"
services:
  app:
    container_name: wtb_app
    build:
      context: .
      dockerfile: Dockerfile
      target: server
    ports:
      - "3000:3000"
    env_file:
      - packages/server/.env
    volumes:
      - ./docker_data/uploads:/app/uploads
      - ./docker_data/api_logs:/app/api_logs
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
    volumes:
      - ./docker_data/uploads:/usr/share/nginx/html/uploads
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./docker_data/certbot/www/:/var/www/certbot/:rw
      - ./docker_data/certbot/conf/:/etc/letsencrypt/:rw
    entrypoint: |
      sh -c "
        certbot certonly --webroot -w /var/www/certbot -d waytochess.site --email ignatmustafin77@gmail.com --agree-tos --non-interactive --keep-until-expiring &&
        sleep 1d &&
        exit 0
      "
    restart: unless-stopped
