FROM node:20.17.0-alpine AS builder-dev

WORKDIR /app

COPY package.json package-lock.json ./
COPY packages/shared/package.json ./packages/shared/
COPY packages/server/package.json ./packages/server/

RUN npm install --workspace @way-to-bot/shared
RUN npm install --workspace @way-to-bot/server

COPY typescript ./typescript
COPY packages/shared ./packages/shared
COPY packages/server ./packages/server

RUN npm run build --workspace @way-to-bot/shared
RUN npm run build --workspace @way-to-bot/server

FROM node:20.17.0-alpine AS server-dev

WORKDIR /app
COPY --from=builder-dev /app/package.json ./package.json
COPY --from=builder-dev /app/package-lock.json ./package-lock.json

COPY --from=builder-dev /app/packages/shared/dist ./packages/shared/dist
COPY --from=builder-dev /app/packages/shared/package.json ./packages/shared/package.json

COPY --from=builder-dev /app/packages/server/dist ./packages/server/dist
COPY --from=builder-dev /app/packages/server/package.json ./packages/server/package.json
COPY --from=builder-dev /app/packages/server/.env ./packages/server/.env
COPY --from=builder-dev /app/packages/server/bin ./packages/server/bin

RUN npm install --production

EXPOSE 3000

