version: "3.9"
services:
  app:
    container_name: wtb_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - packages/server/.env
      - packages/webapp/.env
    volumes:
      - ./docker_data/uploads:/app/uploads
      - ./packages/webapp/dist:/app/packages/webapp/dist
      - ./packages/server/logs:/app/api_logs
    restart: on-failure
    command: >
      sh -c "
        npm run build --workspace @way-to-bot/webapp &&
        npm run build --workspace @way-to-bot/adminui &&
        npm run build --workspace @way-to-bot/server && 
        npm run typeorm:migrate --workspace @way-to-bot/server &&
        npm run production --workspace @way-to-bot/server
      "

  nginx:
    container_name: wtb_nginx
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./packages/webapp/dist:/webapp
      - ./packages/adminui/dist:/admin
      - ./docker_data/uploads:/usr/share/nginx/html/uploads
      - ./docker_data/certbot/www/:/var/www/certbot/:ro
      - ./docker_data/certbot/conf/:/etc/nginx/ssl/:ro
    ports:
      - "80:80"
      - "443:443"
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./docker_data/certbot/www/:/var/www/certbot/:rw
      - ./docker_data/certbot/conf/:/etc/letsencrypt/:rw
