services:
  postgres:
    container_name: wtb_postgres
    image: postgres:15
    env_file:
      - ./packages/server/.env
    restart: on-failure:3
    user: "999:999"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./docker_data/postgres/config/postgresql.conf:/etc/postgresql/postgresql.conf:ro
      - ./docker_data/postgres/config/pg_hba.conf:/etc/postgresql/pg_hba.conf:ro
    ports:
      - "5432:5432"
    command: bash -c "
      docker-entrypoint.sh postgres -c config_file=/etc/postgresql/postgresql.conf -c hba_file=/etc/postgresql/pg_hba.conf
      "
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - FOWNER
      - SETGID
      - SETUID
    healthcheck:
      test:
        ["CMD", "pg_isready", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  app:
    container_name: wtb_app
    build:
      context: .
      dockerfile: Dockerfile
      target: server
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - ./packages/server/.env
    restart: on-failure:3
    volumes:
      - ./docker_data/uploads:/app/docker_data/uploads
      - ./docker_data/api_logs:/app/docker_data/api_logs
    command: >
      sh -c "
        cd packages/server &&
        sh bin/typeorm/run-migration.sh && 
        npm run production
      "

  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx-dev.conf:/etc/nginx/nginx.conf:ro
      - ./docker_data/uploads:/usr/share/nginx/html/uploads
      - ./docker_data/certbot/www/:/var/www/certbot/:ro
      - ./docker_data/certbot/conf/:/etc/nginx/ssl/:ro
    restart: on-failure:3

  certbot:
    container_name: wtb_certbot
    image: certbot/certbot:latest
    volumes:
      - ./docker_data/certbot/www/:/var/www/certbot/:rw
      - ./docker_data/certbot/conf/:/etc/letsencrypt/:rw
    entrypoint: |
      sh -c "
        certbot certonly --webroot -w /var/www/certbot -d waytochess.space --email ignatmustafin77@gmail.com --agree-tos --non-interactive --keep-until-expiring &&
        sleep 1d &&
        exit 0
      "
    restart: on-failure:3

volumes:
  pg_data:
