services:
  app:
    container_name: wtb_app
    image: traktirwik/way_to_bot:server_${TAG:?err}_${ENV:?err}
    ports:
      - "3000:3000"
    env_file:
      - ./packages/server/.env
    volumes:
      - ./packages/server/.env:/app/packages/server/.env
      - ./docker_data/uploads:/app/docker_data/uploads
      - ./docker_data/api_logs:/app/docker_data/api_logs
    restart: on-failure:3
    command: >
      sh -c "
        cd packages/server &&
        sh bin/typeorm/run-migration.sh && 
        npm run production
      "

  web:
    container_name: wtb_web
    image: traktirwik/way_to_bot:web_${TAG:?err}_${ENV:?err}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/service_unavailable:/usr/share/nginx/html/service_unavailable:ro
      - ./docker_data/uploads:/usr/share/nginx/html/uploads
      - ./docker_data/certbot/www/:/var/www/certbot/:ro
      - ./docker_data/certbot/conf/:/etc/nginx/ssl/:ro
    restart: on-failure:3

  certbot:
    container_name: wtb_certbot
    image: certbot/certbot:latest
    volumes:
      - ./docker_data/certbot/www/:/var/www/certbot/:rw
      - ./docker_data/certbot/conf/:/etc/letsencrypt/:rw
    entrypoint: |
      sh -c "
        certbot certonly --webroot -w /var/www/certbot -d waytochess.site --email ignatmustafin77@gmail.com --agree-tos --non-interactive --keep-until-expiring &&
        sleep 1d &&
        exit 0
      "
    restart: on-failure:3
