const TEXT = {
  registrationInto: "У вас нет аккаунта",
  uploadFileEmpty: "Файл не выбран",
  participate: "Участвовать",
  participateRequestIntro:
    "Загрузите чек об оплате чтобы отправить запрос на участие",
  confirmParticipateRequest: "Отправить запрос",
  hasPendingRequest: "Запрос на рассмотрении",
  participateRequests: "Запросы на участие",
  user: "Пользователь",
  event: "Событие",
  status: "Статус",
  waitingStatus: "Ожидает",
  rejectedStatus: "Отклонён",
  approvedStatus: "Подтверждён",
  approve: "Принять",
  showFile: "Показать файл",
  noFile: "Нет прикреплённого файла",
  league: "Лига",
  common: {
    send: "Отправить",
    yes: "Да",
    no: "Нет",
    requiredField: "Обязательное поле",
    create: "Создать",
    events: "События",
    users: "Пользователи",
    upload: "Загрузить",
    edit: "Изменить",
    delete: "Удалить",
    underDevelopment: "В разработке",
    apply: "Применить",
    asc: "От меньшего к большему",
    desc: "От большего к меньшему",
  },
  api: {
    success: "Успех",
    error: "Что-то пошло не так",
  },
  mainMenu: {
    locations: "Локации",
    title: "Главное Меню",
    users: "Пользователи",
    events: "События",
    leagues: "Лиги",
  },
  users: {
    message: "Сообщение",
    users: "Пользователи",
    sendMessage: "Отправить сообщение",
    addUser: "Добавить пользователя",
    sortByUsername: "По имени пользователя",
    sortByRating: "По рейтингу",
    sortByWinRate: "По проценту побед",
    sortBy: "Сортировать",
    wins: "Победы",
    loses: "Поражения",
    draws: "Ничьи",
    winRate: "Процент побед",
    total: "Кол-во партий",
    rating: "Рейтинг",
    statistics: "Статистика",
    username: "Ник в телеграмм",
    firstName: "Имя",
    lastName: "Фамилия",
    roles: "Роли",
    deleteWarn: "Вы уверены, что хотите удалить пользователя?",
  },
  events: {
    name: "Название",
    fileId: "Изображение",
    addUser: "Добавить пользователя",
    addLeague: "Добавить лигу",
    dateTime: "Дата и время",
    price: "Взнос",
    participantsLimit: "Количество участников",
    linkToTable: "Ссылка на таблицу",
    locationId: "Локация",
    leagueId: "Лига",
    userIds: "Пользователи",
    deleteWarn: "Вы уверены, что хотите удалить событие?",
    waiting: "Ожидаем начала",
    finished: "Окончился",
    started: "Начался",
  },
  locations: {
    title: "Название",
    url: "Ссылка",
    address: "Адрес",
    fileId: "Изображение",
    map: "Показать на карте",
  },
  leagues: {
    name: "Название",
  },
};

export { TEXT };
