const TEXT = {
  common: {
    yes: "Да",
    no: "Нет",
    requiredField: "Обязательное поле",
    create: "Создать",
    events: "События",
    users: "Пользователи",
    upload: "Загрузить",
    edit: "Изменить",
    delete: "Удалить",
  },
  api: {
    success: "Успех",
    error: "Что-то пошло не так",
  },
  mainMenu: {
    locations: "Локации",
    title: "Главное Меню",
    users: "Пользователи",
    events: "События",
    leagues: "Лиги",
  },
  users: {
    wins: "Победы",
    loses: "Поражения",
    draws: "Ничьи",
    winRate: "Процент побед",
    total: "Кол-во партий",
    rating: "Рейтинг",
    statistics: "Статистика",
    username: "Ник в телеграмм",
    firstName: "Имя",
    lastName: "Фамилия",
    roles: "Роли",
    deleteWarn: "Вы уверены, что хотите удалить пользователя?",
  },
  manageEvents: {
    name: "Название",
    fileId: "Изображение",
    addUser: "Добавить пользователя",
    addLeague: "Добавить лигу",
    dateTime: "Дата и время",
    price: "Взнос",
    status: "Статус",
    participantsLimit: "Количество участников",
    linkToTable: "Ссылка на таблицу",
    locationId: "Локация",
  },
  locations: {
    title: "Название",
    url: "Ссылка",
    address: "Адрес",
    fileId: "Изображение",
    map: "Показать на карте",
  },
  leagues: {
    name: "Название",
  },
};

export { TEXT };
