import { createRequestSymbol } from "../RequestManager/CreateRequestSymbol";

const LEAGUES_CREATE_REQUEST_SYMBOL = createRequestSymbol("LEAGUES_CREATE");
const LEAGUES_DELETE_REQUEST_SYMBOL = createRequestSymbol("LEAGUES_DELETE");
const LEAGUES_UPDATE_REQUEST_SYMBOL = createRequestSymbol("LEAGUES_UPDATE");
const LEAGUES_LOAD_REQUEST_SYMBOL = createRequestSymbol("LEAGUES_LOAD");

export {
  LEAGUES_CREATE_REQUEST_SYMBOL,
  LEAGUES_DELETE_REQUEST_SYMBOL,
  LEAGUES_UPDATE_REQUEST_SYMBOL,
  LEAGUES_LOAD_REQUEST_SYMBOL,
};
