import { IUser } from "@way-to-bot/shared/interfaces/user.interface";
import { EEventStatus, EUserRole } from "@way-to-bot/shared/enums";
import { LOCATIONS } from "../Locations/LOCATIONS";

export const USERS: IUser[] = [
  {
    id: 1,
    events: [
      {
        id: 1,
        dateTime: Date.now(),
        location: LOCATIONS[0],
        participantsLimit: 20,
        price: "40 BYN",
        status: EEventStatus.WAITING,
        users: [
          {
            id: 1,
            events: [],
            firstName: "Sasha",
            lastName: "Nuke",
            username: "privetenn",
            total: 3,
            wins: 1,
            draws: 1,
            losses: 1,
            rating: 123,
            roles: [EUserRole.USER],
            winRate: 0.5,
            photo: null,
            createdAt: 123,
            updatedAt: 123,
          },
        ],
        updatedAt: 123,
        createdAt: 123,
      },
    ],
    firstName: "Sasha",
    lastName: "MeNuke",
    username: "privetenn",
    total: 3,
    wins: 1,
    draws: 1,
    losses: 1,
    rating: 123,
    roles: [EUserRole.USER],
    winRate: 0.5,
    photo: {
      id: 1,
      url: `https://api.dicebear.com/7.x/miniavs/svg?seed=privetenn`,
    },
    createdAt: 123,
    updatedAt: 123,
  },
  {
    id: 1,
    events: [],
    firstName: "Ignat",
    lastName: "Stuffin",
    username: "traktirwik",
    total: 3,
    wins: 1,
    draws: 1,
    losses: 1,
    rating: 123,
    roles: [EUserRole.USER],
    winRate: 0.5,
    photo: {
      id: 2,
      url: `https://api.dicebear.com/7.x/miniavs/svg?seed=traktirwik`,
    },
    createdAt: 123,
    updatedAt: 123,
  },
];
