import { createRequestSymbol } from "../RequestManager/CreateRequestSymbol";

const PARTICIPATE_REQUEST_CREATE_REQUEST_SYMBOL = createRequestSymbol(
  "PARTICIPATE_REQUEST_CREATE",
);
const PARTICIPATE_REQUEST_DELETE_REQUEST_SYMBOL = createRequestSymbol(
  "PARTICIPATE_REQUEST_DELETE",
);
const PARTICIPATE_REQUEST_UPDATE_REQUEST_SYMBOL = createRequestSymbol(
  "PARTICIPATE_REQUEST_UPDATE",
);

export {
  PARTICIPATE_REQUEST_CREATE_REQUEST_SYMBOL,
  PARTICIPATE_REQUEST_DELETE_REQUEST_SYMBOL,
  PARTICIPATE_REQUEST_UPDATE_REQUEST_SYMBOL,
};
