name: DEV

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v1.0.3

        with:
          host: ${{ secrets.DEV_SERVER_HOST }}
          username: ${{ secrets.DEV_SSH_USERNAME }}
          key: ${{ secrets.DEV_SSH_PRIVATE_KEY }}
          script: |
            cd /home/way-to-bot
            git pull origin dev
            docker compose -f docker-compose.dev.yml up app web -d --build

            # Cleanup
            docker system prune -f --volumes
            docker image prune -f