name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: SSH Remote Commands
      uses: appleboy/ssh-action@v1.0.3
            
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/way-to-bot
          git pull origin master
          . ~/.nvm/nvm.sh
          nvm use default
          docker-compose build
          docker compose up -d
          docker system prune -f
